- name: Demonstrating Privilege Escalation
  hosts: all
  become: yes                          # Privilege Escalation : Runs the whole playbook as a root user.        
  tasks:
    - name: Checking the user id 
      ansible.builtin.shell: id 
      register: OUT
    
    - name: Printing user details
      ansible.builtin.debug:  
        msg: "{{ OUT.stdout }}"