- name: Demo on using loops  
  hosts: all 
  tasks:
    - name: Demo on using loops 1
      ansible.builtin.debug:
        msg: "Value is {{ item }}"
      loop:   
        - 10
        - 20
        - 30